### ISSUE TITLE
Redo roblox-pyc

### ISSUE THREAD

**Issue by AsynchronousAI** [AsynchronousAI/roblox.pyc#11]
This is a big project so any contributions will be appreciated.

### Steps:
**Step 1: Rewrite**
Step 1.1 - Write utility ✅ 
Step 1.2 - Write AST library ✅ 
Step 1.3 - Write source code generator from AST (test with a manual AST) 🟨 
Step 1.4 - Write Python parser and use a binding from python -> lua for Lua Language access
Step 1.5 - Write a C99 and slight C++ parser using python libclang and bind to lua

**Conclude**
Step 2 - Redo the STDLibrary
Step 3 - Add new features and fix bugs
***

**Comment by Ashish-sarmah** [comment]
Hey! assign to me , I want to contribute.
I am a beginner in lua but hint me, I'll do my best.

**Comment by AsynchronousAI** [comment]
@Ashish-sarmah 
Hey there, I appreciate your contribution, you can join the [discord sever](https://devforum.roblox.com/t/roblox-py-python-luau/2457105) or add me (aqzp on discord) or we can talk here if you prefer.
