### ISSUE TITLE
ModuleNotFoundError: No module named 'colortext'

### ISSUE THREAD

**Issue by luxkatana** [AsynchronousAI/roblox.pyc#20]
currently, when running ``rpyc`` in gives me the error that the module ``colortext`` does not exist, what module (or package) do I have to install to fix this issue?

*Currently running this project by python3.11 on Windows*

**Comment by luxkatana** [comment]
When building it myself  it says 
```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1702: character maps to <undefined>
```
Is it not supported yet for  3.11?

**Comment by AsynchronousAI** [comment]
Python has a huge problem with importing from CLI and terminal, I was planning on fixing this in the rewriting but I can fix it rn. It is supported for 3.11, could you provide when this error happens?

**Comment by luxkatana** [comment]
> Python has a huge problem with importing from CLI and terminal, I was planning on fixing this in the rewriting but I can fix it rn. It is supported for 3.11, could you provide when this error happens?

It throws me that exception when executing the "rpyc" command.

**Comment by AsynchronousAI** [comment]
Will look into it thank you.

**Comment by AsynchronousAI** [comment]
@all-contributors please add @luxkatana for bug
